### ISSUE TITLE
macOS build instructions

### ISSUE THREAD

**Issue by foreverigor** [TagStudioDev/TagStudio#20]
I managed to build & run on macOS so I'm sharing:

It didn't work with the latest version of python, something related to dependencies, but 3.10 works so try with that.
I recommend using [mise](https://github.com/jdx/mise#quickstart) for installation of python, it can also handle the rest of the build. Using mise, this is how you build on macOS (and potentially linux)

Put this into a file called `.mise.toml` in the project directory
```toml
[tools]
python = "3.10"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.tagstudio]
run = "pip install -r requirements.txt && python tagstudio/tagstudio.py"
```
and then run (with installed mise) `mise trust && mise install`, this will install python and create the venv and you can run the normal linux/ macos build instruction, or alternatively use `mise run --yes tagstudio` one-liner

the app & gui starts but looks a little fucky
